INSERT INTO "user"(name, surname, avatar, username, role) VALUES
('Reinel', 'Arteaga', 'https://cdnb.artstation.com/p/assets/images/images/035/988/597/large/edward-munn-edm-asset.jpg?1616441586', 'reinel-1', 'user'),
('Juan', 'Perez', 'https://cdnb.artstation.com/p/assets/images/images/035/988/597/large/edward-munn-edm-asset.jpg?1616441586', 'juanito', 'user'),
('Pedro', 'Admin', 'https://cdnb.artstation.com/p/assets/images/images/035/988/597/large/edward-munn-edm-asset.jpg?1616441586', 'pedro', 'admin');
insert into "user" ("name", surname, avatar, username, "role") values ('Gladi', 'Luard', 'http://dummyimage.com/246x100.png/ff4444/ffffff', 'gluard1', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Abigale', 'Molines', 'http://dummyimage.com/141x100.png/dddddd/000000', 'amolines0', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Cristiano', 'Cremen', 'http://dummyimage.com/150x100.png/ff4444/ffffff', 'ccremen2', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Aeriela', 'Dendle', 'http://dummyimage.com/135x100.png/5fa2dd/ffffff', 'adendle3', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Blondie', 'O''Mailey', 'http://dummyimage.com/228x100.png/dddddd/000000', 'bomailey4', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Amerigo', 'Sweating', 'http://dummyimage.com/119x100.png/ff4444/ffffff', 'asweating5', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Shelley', 'Tubridy', 'http://dummyimage.com/118x100.png/dddddd/000000', 'stubridy6', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Norene', 'Yakovitch', 'http://dummyimage.com/156x100.png/5fa2dd/ffffff', 'nyakovitch7', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Linus', 'Orthmann', 'http://dummyimage.com/137x100.png/5fa2dd/ffffff', 'lorthmann8', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Neill', 'Anten', 'http://dummyimage.com/194x100.png/5fa2dd/ffffff', 'nanten9', 'admin');
insert into "user" ("name", surname, avatar, username, "role") values ('Timmy', 'Given', 'http://dummyimage.com/156x100.png/ff4444/ffffff', 'tgivena', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Jackie', 'Zanuciolii', 'http://dummyimage.com/114x100.png/ff4444/ffffff', 'jzanucioliib', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Dorie', 'Greenrodd', 'http://dummyimage.com/105x100.png/ff4444/ffffff', 'dgreenroddc', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Penni', 'Flipek', 'http://dummyimage.com/125x100.png/cc0000/ffffff', 'pflipekd', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Bobby', 'Cowser', 'http://dummyimage.com/193x100.png/dddddd/000000', 'bcowsere', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Joeann', 'Guiot', 'http://dummyimage.com/197x100.png/5fa2dd/ffffff', 'jguiotf', 'admin');
insert into "user" ("name", surname, avatar, username, "role") values ('Blakeley', 'Youings', 'http://dummyimage.com/217x100.png/dddddd/000000', 'byouingsg', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Thatch', 'Mussington', 'http://dummyimage.com/121x100.png/5fa2dd/ffffff', 'tmussingtonh', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Cyrus', 'Prugel', 'http://dummyimage.com/202x100.png/cc0000/ffffff', 'cprugeli', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Crissy', 'Smeeth', 'http://dummyimage.com/237x100.png/5fa2dd/ffffff', 'csmeethj', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Valida', 'Kosiada', 'http://dummyimage.com/138x100.png/cc0000/ffffff', 'vkosiadak', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Ase', 'Snyder', 'http://dummyimage.com/108x100.png/dddddd/000000', 'asnyderl', 'admin');
insert into "user" ("name", surname, avatar, username, "role") values ('Othello', 'Quinnell', 'http://dummyimage.com/236x100.png/ff4444/ffffff', 'oquinnellm', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Desmond', 'Twiggins', 'http://dummyimage.com/208x100.png/ff4444/ffffff', 'dtwigginsn', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Rubina', 'Bonwell', 'http://dummyimage.com/244x100.png/ff4444/ffffff', 'rbonwello', 'user');
insert into "user" ("name", surname, avatar, username, "role") values ('Mae', 'Cotgrave', 'http://dummyimage.com/242x100.png/ff4444/ffffff', 'mcotgravep', 'admin');
insert into "user" ("name", surname, avatar, username, "role") values ('Alexander', 'Hamfleet', 'http://dummyimage.com/168x100.png/cc0000/ffffff', 'ahamfleetq', 'user');


INSERT INTO post(message, user_id, location, status) VALUES
('Hellow everybody! lets bring the avatar down today!', 1, 'venezuela', 'drafted'),
('Hellow everybody! lets bring the avatar down today 2!', 1, 'venezuela', 'drafted'),
('Hellow everybody! lets bring the avatar down today 3!', 2, 'brazil', 'drafted');



insert into post (message, user_id, location, status, image) values ('Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 14, 'EG', 'published', 'http://dummyimage.com/330x321.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 3, 'US', 'published', 'http://dummyimage.com/330x305.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 25, 'KZ', 'published', 'http://dummyimage.com/348x370.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 9, 'TH', 'published', 'http://dummyimage.com/390x346.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 10, 'FI', 'published', 'http://dummyimage.com/313x390.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 11, 'CD', 'published', 'http://dummyimage.com/386x351.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 15, 'PH', 'published', 'http://dummyimage.com/342x359.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 5, 'IT', 'published', 'http://dummyimage.com/386x300.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 16, 'US', 'published', 'http://dummyimage.com/330x398.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 20, 'US', 'published', 'http://dummyimage.com/328x367.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Phasellus in felis. Donec semper sapien a libero. Nam dui.', 16, 'AR', 'published', 'http://dummyimage.com/324x310.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1, 'IN', 'published', 'http://dummyimage.com/357x341.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 11, 'US', 'published', 'http://dummyimage.com/370x372.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 16, 'AU', 'published', 'http://dummyimage.com/398x350.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 19, 'VE', 'published', 'http://dummyimage.com/350x342.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 10, 'US', 'published', 'http://dummyimage.com/351x300.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Phasellus in felis. Donec semper sapien a libero. Nam dui.', 4, 'KE', 'published', 'http://dummyimage.com/352x316.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 12, 'US', 'published', 'http://dummyimage.com/385x399.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 12, 'CA', 'published', 'http://dummyimage.com/318x300.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 5, 'MY', 'published', 'http://dummyimage.com/373x345.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 6, 'CA', 'published', 'http://dummyimage.com/315x346.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 10, 'CL', 'published', 'http://dummyimage.com/304x321.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 7, 'BR', 'published', 'http://dummyimage.com/300x310.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 15, 'BR', 'published', 'http://dummyimage.com/370x333.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 13, 'CO', 'published', 'http://dummyimage.com/313x331.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 25, 'CU', 'published', 'http://dummyimage.com/333x363.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 26, 'IN', 'published', 'http://dummyimage.com/379x347.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 24, 'US', 'published', 'http://dummyimage.com/348x342.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 11, 'BR', 'published', 'http://dummyimage.com/398x394.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 9, 'JP', 'published', 'http://dummyimage.com/374x301.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 13, 'JP', 'published', 'http://dummyimage.com/310x318.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 7, 'US', 'published', 'http://dummyimage.com/395x333.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 24, 'US', 'published', 'http://dummyimage.com/346x386.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 15, 'CA', 'published', 'http://dummyimage.com/399x369.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 13, 'US', 'published', 'http://dummyimage.com/302x329.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('In congue. Etiam justo. Etiam pretium iaculis justo.', 23, 'DE', 'published', 'http://dummyimage.com/352x331.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 8, 'BR', 'published', 'http://dummyimage.com/381x300.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 27, 'CA', 'published', 'http://dummyimage.com/361x394.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 16, 'PG', 'published', 'http://dummyimage.com/309x322.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1, 'CD', 'published', 'http://dummyimage.com/332x366.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 30, 'IR', 'published', 'http://dummyimage.com/336x373.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 18, 'RU', 'deleted', 'http://dummyimage.com/348x326.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 29, 'ID', 'deleted', 'http://dummyimage.com/345x301.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 23, 'MX', 'deleted', 'http://dummyimage.com/348x310.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 12, 'AR', 'deleted', 'http://dummyimage.com/327x375.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 23, 'US', 'deleted', 'http://dummyimage.com/301x352.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 8, 'CZ', 'deleted', 'http://dummyimage.com/314x318.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 12, 'US', 'deleted', 'http://dummyimage.com/309x309.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 10, 'SE', 'deleted', 'http://dummyimage.com/367x388.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('In congue. Etiam justo. Etiam pretium iaculis justo.', 11, 'PG', 'deleted', 'http://dummyimage.com/348x302.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 9, 'VN', 'deleted', 'http://dummyimage.com/328x372.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 3, 'CD', 'deleted', 'http://dummyimage.com/358x349.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 27, 'UZ', 'deleted', 'http://dummyimage.com/392x351.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 18, 'RU', 'deleted', 'http://dummyimage.com/387x361.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1, 'PG', 'deleted', 'http://dummyimage.com/390x367.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 12, 'US', 'deleted', 'http://dummyimage.com/336x310.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 26, 'SO', 'deleted', 'http://dummyimage.com/381x398.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 18, 'BR', 'deleted', 'http://dummyimage.com/315x353.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 28, 'CR', 'deleted', 'http://dummyimage.com/356x387.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Fusce consequat. Nulla nisl. Nunc nisl.', 16, 'RU', 'deleted', 'http://dummyimage.com/326x386.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('In congue. Etiam justo. Etiam pretium iaculis justo.', 22, 'RO', 'deleted', 'http://dummyimage.com/354x323.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('In congue. Etiam justo. Etiam pretium iaculis justo.', 4, 'LY', 'deleted', 'http://dummyimage.com/392x399.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 26, 'US', 'deleted', 'http://dummyimage.com/311x311.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 5, 'PH', 'deleted', 'http://dummyimage.com/330x317.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 29, 'CA', 'deleted', 'http://dummyimage.com/313x366.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 11, 'MR', 'deleted', 'http://dummyimage.com/330x345.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1, 'AU', 'deleted', 'http://dummyimage.com/373x400.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 13, 'US', 'deleted', 'http://dummyimage.com/313x374.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 9, 'FI', 'deleted', 'http://dummyimage.com/386x326.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 11, 'RU', 'deleted', 'http://dummyimage.com/350x391.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Fusce consequat. Nulla nisl. Nunc nisl.', 9, 'BF', 'deleted', 'http://dummyimage.com/380x309.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 9, 'MX', 'deleted', 'http://dummyimage.com/348x371.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 5, 'CN', 'deleted', 'http://dummyimage.com/307x316.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 6, 'CD', 'deleted', 'http://dummyimage.com/399x378.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 27, 'PA', 'deleted', 'http://dummyimage.com/334x362.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 2, 'ET', 'deleted', 'http://dummyimage.com/360x337.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 23, 'DJ', 'deleted', 'http://dummyimage.com/310x323.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 18, 'YE', 'deleted', 'http://dummyimage.com/319x331.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 11, 'GL', 'deleted', 'http://dummyimage.com/398x358.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 27, 'EG', 'deleted', 'http://dummyimage.com/345x363.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 29, 'KE', 'deleted', 'http://dummyimage.com/312x323.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 5, 'AU', 'deleted', 'http://dummyimage.com/325x399.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 29, 'CA', 'deleted', 'http://dummyimage.com/363x377.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 23, 'RU', 'drafted', 'http://dummyimage.com/304x361.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Fusce consequat. Nulla nisl. Nunc nisl.', 25, 'BR', 'drafted', 'http://dummyimage.com/351x314.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 11, 'HU', 'drafted', 'http://dummyimage.com/371x398.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 16, 'US', 'drafted', 'http://dummyimage.com/316x326.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 12, 'US', 'drafted', 'http://dummyimage.com/312x387.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1, 'MY', 'drafted', 'http://dummyimage.com/384x331.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 22, 'BR', 'drafted', 'http://dummyimage.com/390x336.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 30, 'US', 'drafted', 'http://dummyimage.com/395x343.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 21, 'VC', 'drafted', 'http://dummyimage.com/372x304.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 3, 'TR', 'drafted', 'http://dummyimage.com/324x313.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 19, 'US', 'drafted', 'http://dummyimage.com/308x380.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 16, 'CI', 'drafted', 'http://dummyimage.com/371x347.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 23, 'US', 'drafted', 'http://dummyimage.com/349x394.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 20, 'CR', 'drafted', 'http://dummyimage.com/327x318.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 8, 'US', 'drafted', 'http://dummyimage.com/304x334.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 8, 'AF', 'drafted', 'http://dummyimage.com/355x378.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 4, 'US', 'drafted', 'http://dummyimage.com/315x349.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 5, 'CN', 'drafted', 'http://dummyimage.com/316x355.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 16, 'US', 'drafted', 'http://dummyimage.com/349x320.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 29, 'US', 'drafted', 'http://dummyimage.com/386x386.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 20, 'US', 'drafted', 'http://dummyimage.com/321x335.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 3, 'FR', 'drafted', 'http://dummyimage.com/384x355.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 23, 'JP', 'drafted', 'http://dummyimage.com/312x396.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 13, 'YE', 'drafted', 'http://dummyimage.com/321x337.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 24, 'CH', 'drafted', 'http://dummyimage.com/366x385.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 13, 'CN', 'drafted', 'http://dummyimage.com/303x318.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 16, 'DE', 'drafted', 'http://dummyimage.com/389x331.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 5, 'CA', 'drafted', 'http://dummyimage.com/369x314.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 18, 'ES', 'drafted', 'http://dummyimage.com/371x384.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 2, 'IT', 'drafted', 'http://dummyimage.com/390x367.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 19, 'NO', 'drafted', 'http://dummyimage.com/397x347.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 22, 'AU', 'drafted', 'http://dummyimage.com/400x314.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 2, 'OM', 'drafted', 'http://dummyimage.com/373x306.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 16, 'US', 'drafted', 'http://dummyimage.com/332x362.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 9, 'DE', 'drafted', 'http://dummyimage.com/381x331.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 11, 'US', 'drafted', 'http://dummyimage.com/392x372.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 24, 'BO', 'drafted', 'http://dummyimage.com/307x386.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 16, 'CA', 'drafted', 'http://dummyimage.com/359x300.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 2, 'IT', 'drafted', 'http://dummyimage.com/360x341.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 19, 'ID', 'drafted', 'http://dummyimage.com/330x380.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 19, 'US', 'drafted', 'http://dummyimage.com/345x313.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 28, 'BR', 'drafted', 'http://dummyimage.com/309x324.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 21, 'CO', 'drafted', 'http://dummyimage.com/337x312.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 3, 'AU', 'drafted', 'http://dummyimage.com/317x329.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 6, 'US', 'drafted', 'http://dummyimage.com/319x383.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 13, 'CG', 'drafted', 'http://dummyimage.com/343x319.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 5, 'US', 'drafted', 'http://dummyimage.com/312x379.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 10, 'CH', 'drafted', 'http://dummyimage.com/396x381.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 9, 'DM', 'drafted', 'http://dummyimage.com/320x326.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 10, 'IN', 'drafted', 'http://dummyimage.com/314x345.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 14, 'BR', 'drafted', 'http://dummyimage.com/320x384.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1, 'BS', 'drafted', 'http://dummyimage.com/314x342.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 14, 'NZ', 'drafted', 'http://dummyimage.com/306x345.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 23, 'IL', 'drafted', 'http://dummyimage.com/323x385.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 7, 'DE', 'drafted', 'http://dummyimage.com/393x378.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 25, 'VU', 'drafted', 'http://dummyimage.com/310x310.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 7, 'US', 'drafted', 'http://dummyimage.com/328x389.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1, 'US', 'drafted', 'http://dummyimage.com/316x385.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 21, 'PE', 'drafted', 'http://dummyimage.com/373x378.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 25, 'FJ', 'drafted', 'http://dummyimage.com/318x328.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 6, 'US', 'drafted', 'http://dummyimage.com/314x389.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 24, 'EG', 'drafted', 'http://dummyimage.com/391x373.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 14, 'PF', 'drafted', 'http://dummyimage.com/397x393.png/5fa2dd/ffffff');
insert into post (message, user_id, location, status, image) values ('Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 14, 'GB', 'drafted', 'http://dummyimage.com/391x348.png/cc0000/ffffff');
insert into post (message, user_id, location, status, image) values ('In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1, 'US', 'drafted', 'http://dummyimage.com/355x340.png/dddddd/000000');
insert into post (message, user_id, location, status, image) values ('Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 12, 'BG', 'drafted', 'http://dummyimage.com/324x301.png/ff4444/ffffff');
insert into post (message, user_id, location, status, image) values ('Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 12, 'US', 'drafted', 'http://dummyimage.com/339x318.png/5fa2dd/ffffff');


INSERT INTO "like"(user_id, post_id) VALUES
(1,1),
(2,2),
(1,3);


insert into "like" (user_id, post_id) values (6, 57);
insert into "like" (user_id, post_id) values (16, 98);
insert into "like" (user_id, post_id) values (5, 77);
insert into "like" (user_id, post_id) values (3, 104);
insert into "like" (user_id, post_id) values (23, 41);
insert into "like" (user_id, post_id) values (16, 111);
insert into "like" (user_id, post_id) values (11, 116);
insert into "like" (user_id, post_id) values (22, 19);
insert into "like" (user_id, post_id) values (18, 83);
insert into "like" (user_id, post_id) values (27, 96);
insert into "like" (user_id, post_id) values (19, 69);
insert into "like" (user_id, post_id) values (29, 35);
insert into "like" (user_id, post_id) values (25, 8);
insert into "like" (user_id, post_id) values (15, 130);
insert into "like" (user_id, post_id) values (8, 6);
insert into "like" (user_id, post_id) values (23, 42);
insert into "like" (user_id, post_id) values (7, 89);
insert into "like" (user_id, post_id) values (17, 84);
insert into "like" (user_id, post_id) values (2, 109);
insert into "like" (user_id, post_id) values (6, 106);
insert into "like" (user_id, post_id) values (4, 81);
insert into "like" (user_id, post_id) values (4, 105);
insert into "like" (user_id, post_id) values (16, 71);
insert into "like" (user_id, post_id) values (7, 63);
insert into "like" (user_id, post_id) values (24, 41);
insert into "like" (user_id, post_id) values (30, 128);
insert into "like" (user_id, post_id) values (12, 76);
insert into "like" (user_id, post_id) values (24, 27);
insert into "like" (user_id, post_id) values (26, 49);
insert into "like" (user_id, post_id) values (20, 62);
insert into "like" (user_id, post_id) values (22, 138);
insert into "like" (user_id, post_id) values (4, 141);
insert into "like" (user_id, post_id) values (13, 93);
insert into "like" (user_id, post_id) values (9, 78);
insert into "like" (user_id, post_id) values (12, 136);
insert into "like" (user_id, post_id) values (27, 64);
insert into "like" (user_id, post_id) values (30, 89);
insert into "like" (user_id, post_id) values (26, 92);
insert into "like" (user_id, post_id) values (21, 56);
insert into "like" (user_id, post_id) values (3, 30);
insert into "like" (user_id, post_id) values (19, 66);
insert into "like" (user_id, post_id) values (20, 39);
insert into "like" (user_id, post_id) values (4, 83);
insert into "like" (user_id, post_id) values (4, 124);
insert into "like" (user_id, post_id) values (20, 94);
insert into "like" (user_id, post_id) values (20, 59);
insert into "like" (user_id, post_id) values (22, 28);
insert into "like" (user_id, post_id) values (17, 98);
insert into "like" (user_id, post_id) values (2, 125);
insert into "like" (user_id, post_id) values (26, 91);
insert into "like" (user_id, post_id) values (2, 52);
insert into "like" (user_id, post_id) values (15, 144);
insert into "like" (user_id, post_id) values (22, 1);
insert into "like" (user_id, post_id) values (30, 71);
insert into "like" (user_id, post_id) values (3, 124);
insert into "like" (user_id, post_id) values (3, 81);
insert into "like" (user_id, post_id) values (8, 52);
insert into "like" (user_id, post_id) values (16, 20);
insert into "like" (user_id, post_id) values (18, 110);
insert into "like" (user_id, post_id) values (17, 12);
insert into "like" (user_id, post_id) values (20, 77);
insert into "like" (user_id, post_id) values (13, 94);
insert into "like" (user_id, post_id) values (17, 21);
insert into "like" (user_id, post_id) values (27, 80);
insert into "like" (user_id, post_id) values (28, 108);
insert into "like" (user_id, post_id) values (9, 100);
insert into "like" (user_id, post_id) values (8, 89);
insert into "like" (user_id, post_id) values (4, 25);
insert into "like" (user_id, post_id) values (6, 8);
insert into "like" (user_id, post_id) values (11, 26);
insert into "like" (user_id, post_id) values (21, 109);
insert into "like" (user_id, post_id) values (11, 133);
insert into "like" (user_id, post_id) values (14, 66);
insert into "like" (user_id, post_id) values (30, 81);
insert into "like" (user_id, post_id) values (30, 97);
insert into "like" (user_id, post_id) values (4, 3);
insert into "like" (user_id, post_id) values (10, 30);
insert into "like" (user_id, post_id) values (30, 6);
insert into "like" (user_id, post_id) values (1, 142);
insert into "like" (user_id, post_id) values (23, 53);
insert into "like" (user_id, post_id) values (7, 57);
insert into "like" (user_id, post_id) values (23, 33);
insert into "like" (user_id, post_id) values (4, 98);
insert into "like" (user_id, post_id) values (3, 7);
insert into "like" (user_id, post_id) values (18, 111);
insert into "like" (user_id, post_id) values (10, 56);
insert into "like" (user_id, post_id) values (26, 106);
insert into "like" (user_id, post_id) values (27, 30);
insert into "like" (user_id, post_id) values (11, 108);
insert into "like" (user_id, post_id) values (2, 89);
insert into "like" (user_id, post_id) values (25, 113);
insert into "like" (user_id, post_id) values (17, 135);
insert into "like" (user_id, post_id) values (10, 23);
insert into "like" (user_id, post_id) values (6, 70);
insert into "like" (user_id, post_id) values (10, 54);
insert into "like" (user_id, post_id) values (1, 24);
insert into "like" (user_id, post_id) values (24, 117);
insert into "like" (user_id, post_id) values (23, 36);
insert into "like" (user_id, post_id) values (11, 145);
insert into "like" (user_id, post_id) values (14, 148);
insert into "like" (user_id, post_id) values (6, 145);
insert into "like" (user_id, post_id) values (2, 47);
insert into "like" (user_id, post_id) values (6, 6);
insert into "like" (user_id, post_id) values (19, 135);
insert into "like" (user_id, post_id) values (8, 8);
insert into "like" (user_id, post_id) values (12, 18);
insert into "like" (user_id, post_id) values (19, 35);
insert into "like" (user_id, post_id) values (14, 40);
insert into "like" (user_id, post_id) values (3, 141);
insert into "like" (user_id, post_id) values (23, 47);
insert into "like" (user_id, post_id) values (9, 18);
insert into "like" (user_id, post_id) values (11, 3);
insert into "like" (user_id, post_id) values (13, 74);
insert into "like" (user_id, post_id) values (12, 101);
insert into "like" (user_id, post_id) values (4, 140);
insert into "like" (user_id, post_id) values (18, 132);
insert into "like" (user_id, post_id) values (16, 23);
insert into "like" (user_id, post_id) values (10, 107);
insert into "like" (user_id, post_id) values (12, 105);
insert into "like" (user_id, post_id) values (4, 28);
insert into "like" (user_id, post_id) values (13, 111);
insert into "like" (user_id, post_id) values (1, 143);
insert into "like" (user_id, post_id) values (21, 46);
insert into "like" (user_id, post_id) values (18, 47);
insert into "like" (user_id, post_id) values (28, 20);
insert into "like" (user_id, post_id) values (12, 75);
insert into "like" (user_id, post_id) values (3, 102);
insert into "like" (user_id, post_id) values (27, 100);
insert into "like" (user_id, post_id) values (2, 26);
insert into "like" (user_id, post_id) values (30, 119);
insert into "like" (user_id, post_id) values (5, 134);
insert into "like" (user_id, post_id) values (1, 44);
insert into "like" (user_id, post_id) values (14, 75);
insert into "like" (user_id, post_id) values (7, 122);
insert into "like" (user_id, post_id) values (4, 126);
insert into "like" (user_id, post_id) values (9, 99);
insert into "like" (user_id, post_id) values (1, 92);
insert into "like" (user_id, post_id) values (23, 67);
insert into "like" (user_id, post_id) values (6, 140);
insert into "like" (user_id, post_id) values (4, 41);
insert into "like" (user_id, post_id) values (3, 82);
insert into "like" (user_id, post_id) values (9, 149);
insert into "like" (user_id, post_id) values (30, 5);
insert into "like" (user_id, post_id) values (9, 119);
insert into "like" (user_id, post_id) values (5, 21);
insert into "like" (user_id, post_id) values (13, 79);
insert into "like" (user_id, post_id) values (15, 143);
insert into "like" (user_id, post_id) values (17, 141);
insert into "like" (user_id, post_id) values (26, 51);